on:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: remojuapp-v3u    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/RemojuApp-V3U'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        # npm run build --prod
        npm run build:ssr
    
    - name: 'Move web.config to root'
      run: mv dist/RemojuApp-V3U/browser/web.config dist/RemojuApp-V3U/

    - name: 'Move main.js and Remove server folder'
      run: |
        mv dist/RemojuApp-V3U/server/main.js dist/RemojuApp-V3U/
        rm -rf dist/RemojuApp-V3U/server
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_REMOJUAPPV3U }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
